spring.application.name=devedor

spring.profiles.include=local

# Configurações do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/controle

# O Hibernate vai criar/atualizar a tabela automaticamente
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Exibe o SQL formatado no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Exibe os valores dos parâmetros que estão sendo enviados para o banco
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.liquibase=DEBUG
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG

# Ativa o Liquibase e aponta para o arquivo mestre
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
